apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-pods-ingress
  labels:
    app: k8s-pods-ingress
spec:
  replicas: 1
  selector:
    app: k8s-pods-ingress
  template:
    metadata:
      labels:
        app: k8s-pods-ingress
    spec:
      containers:
      - image: 192.168.64.1:5000/k8s-pods-ingress
        imagePullPolicy: Always
        name: k8s-pods-ingress
        ports:
        - containerPort: 80
          hostPort: 80
