apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8s-pods-ingress
  labels:
    app: k8s-pods-ingress
spec:
  template:
    metadata:
      labels:
        app: k8s-pods-ingress
    spec:
      containers:
      - image: whitlockjc/k8s-pods-ingress:v0
        imagePullPolicy: Always
        name: k8s-pods-ingress
        ports:
          - containerPort: 80
            hostPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
