apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8s-router
  labels:
    app: k8s-router
spec:
  template:
    metadata:
      labels:
        app: k8s-router
    spec:
      containers:
      - image: thirtyx/k8s-router:latest
        imagePullPolicy: Always
        name: k8s-router
        ports:
          - containerPort: 80
            hostPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
