apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-k8s-env
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-k8s-env
        routable: "true"
      annotations:
        routingHosts: "test.k8s.local"
        routingPaths: "3000:/nodejs"
    spec:
      containers:
      - name: nodejs-k8s-env
        image: thirtyx/nodejs-k8s-env:latest
        env:
          - name: PORT
            value: "3000"
        ports:
          - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BASE_PATH
            value: /nodejs
